### ISSUE TITLE
"Python is not installed"

### ISSUE THREAD

**Issue by JoshRiser** [cheahjs/palworld-save-tools#21]
I keep getting a message saying Python is not installed when trying to convert a sav to json. I have python installed, and I can see it print the python version. Do I need to have a very specific version? I installed the latest stable version (3.12.1)

![python-error](https://github.com/cheahjs/palworld-save-tools/assets/1509348/9a4283a6-417e-45f7-a0c7-110cf97e2551)

**Comment by Zevgor** [comment]
It looks like it needs to have 'python3' resolve as an execution of Python - I had the same issue. Just open a new CMD window, type 'python3' and install from the WIndows store.

**Comment by cheahjs** [comment]
[v0.6](https://github.com/cheahjs/palworld-save-tools/releases/tag/v0.6) should fix the batch script to properly search for a Python installation (either installed as `python3`, `python`, or `py`).

**Comment by PepGames** [comment]
I am still having this issue on v0.6

EDIT: Do we need python 12? I have 7-11 but none of those worked, downloading python from microsoft store now instead of pythons site.

**Comment by JoshRiser** [comment]
> I am still having this issue on v0.6

Same. Installing python3 from the Microsoft Store did fix it for me.

**Comment by rkocour** [comment]
Same issue. Downgrading to 4.1 works. but any version after it up to 7.1 didn't see my python 3.10 installation. Upgrading to 3.12 to see if that makes a difference

**Comment by Rofltofl** [comment]
For all having issues using the script, first time i had the same. Just change the checked version in the bat/cmd file to your installed version i. e. i had to change "python3" to "python311" as i have 3.11.3 installed.
![github-help](https://github.com/cheahjs/palworld-save-tools/assets/86147164/21b69ec2-dcf8-4bd7-8cb5-2724576bff6d)

**Comment by Rotnam** [comment]
I have seen something similar in the past. This might help: There is a function in Windows that call the microsoft store if you type python.exe or python3.exe, you might want to disable that. It's called "App Execution Aliases" (manage app execution aliases in windows).

**Comment by Jernee** [comment]
> I have seen something similar in the past. This might help: There is a function in Windows that call the microsoft store if you type python.exe or python3.exe, you might want to disable that. It's called "App Execution Aliases" (manage app execution aliases in windows).

This worked for me, had the exact same problem.

**Comment by rkocour** [comment]
I ripped out all my python installs (appdata, install path, and path records) and re-installed from windows store version 3.12 and it seemed to work.

**Comment by Rotnam** [comment]
Not much to do with this project, should probably add in the readme.MD that disabling python/python3 in App Execution Aliases fix this issue if you have the regular python installed.

**Comment by Keinta15** [comment]
> I have seen something similar in the past. This might help: There is a function in Windows that call the microsoft store if you type python.exe or python3.exe, you might want to disable that. It's called "App Execution Aliases" (manage app execution aliases in windows).

This is what worked for me too
